version: 0.0
os: linux

files:
  - source: /
    destination: /home/admin/consultancy-cms

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: deploy/after-install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deploy/start-service.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: deploy/validate-service.sh
      timeout: 60
      runas: root
